import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="section">
                <div className="container">
                    <h1 className="title">
                        Welcome to The Upper Five Tech Share
                    </h1>
                    <p>
                        Here you will find a start to finish web app that allows
                        a user to upload an image to their browser or take a
                        picture with their camera. Then, the image gets uploaded
                        to a database for future use. Click on a page to try out
                        all the features.
                    </p>
                </div>
            </div>
        </>
    );
}
